@startuml

participant ExportDataService
participant DataFieldsAdminRepository
participant DataFieldsManagerRepository
participant DataFieldsLocationRepository
participant DataFieldsInstructorRepository
participant DataFieldsActivitiesRepository
participant DataFieldsChargesRepository
participant DataFieldsParentContactRepository
participant DataFieldsChildRegistrationRepository

ExportDataService -> DataFieldsAdminRepository: findAll()
ExportDataService -> DataFieldsManagerRepository: findAll()
ExportDataService -> DataFieldsLocationRepository: findAll()
ExportDataService -> DataFieldsInstructorRepository: findAll()
ExportDataService -> DataFieldsActivitiesRepository: findAll()
ExportDataService -> DataFieldsChargesRepository: findAll()
ExportDataService -> DataFieldsParentContactRepository: findAll()
ExportDataService -> DataFieldsChildRegistrationRepository: findAll()

activate ExportDataService
DataFieldsAdminRepository -> ExportDataService: List<DataFieldsAdmin>
ExportDataService -> ExportDataService: write admin data to AdminManagerLocation excel
DataFieldsManagerRepository -> ExportDataService: List<DataFieldsManager>
ExportDataService -> ExportDataService: write manager data to AdminManagerLocation excel
DataFieldsLocationRepository -> ExportDataService: List<DataFieldsLocation>
ExportDataService -> ExportDataService: write location data to AdminManagerLocation excel
DataFieldsInstructorRepository -> ExportDataService: List<DataFieldsInstructor>
ExportDataService -> ExportDataService: write instructor data to Instructor excel
DataFieldsActivitiesRepository -> ExportDataService: List<DataFieldsActivities>
ExportDataService -> ExportDataService: write activity data to Activity excel
DataFieldsChargesRepository -> ExportDataService: List<DataFieldsCharges>
ExportDataService -> ExportDataService: write charges data to Charges excel
DataFieldsParentContactRepository -> ExportDataService: List<DataFieldsParentContact>
ExportDataService -> ExportDataService: write parent data to ParentChild excel
DataFieldsChildRegistrationRepository -> ExportDataService: List<DataFieldsChild>
ExportDataService -> ExportDataService: write child data to ParentChild excel
deactivate ExportDataService

@enduml