
@startuml
class ExportController {
    - exportService : ExportDataService

    + exportData() : String
    + exportInstructorData() : String
}

class ExportDataService {
}

ExportController --> "1" ExportDataService : uses

@enduml
