@startuml
left to right direction
actor "Admin" as A
rectangle "Admin Management System" {
  (Access Dashboard) as UC1
  (Create Manager/Admin) as UC3
  (Export Data) as UC5
  (Delete User) as UC6
  (Reset Password) as UC8
}

A -- UC1
A -- UC3
A -- UC5
A -- UC6
A -- UC8
@enduml